#!/bin/bash

mkdir -p $HOME/.local/share/glib-2.0/schemas
cp ./schemas/org.gnome.shell.extensions.brngout.gschema.xml $HOME/.local/share/glib-2.0/schemas/
cd $HOME/.local/share/glib-2.0/schemas
glib-compile-schemas .
exit
